[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
svm_smartcontract = "HpY1m9BGSJKdzMUaZzboRhoicTUjePvXqVSz5UrKScnu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/minhbear/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
